{
 "title": "locust - monitoring - promethues",
 "time": { "from": "now", "to": "now" },
 "panels": [
  {
   "title": "All response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"locustio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requests_login\")\r\n  |> filter(fn: (r) => r[\"query\"] == \"POST/api/login\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"locustio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"requests_single_user\")\r\n  |> filter(fn: (r) => r[\"query\"] == \"GET/api/users?page_equal_two\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_status{job=\"locust\"}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "num_requests" }
   ]
  },
  {
   "title": "Fails requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "num_failures" }
   ]
  },
  {
   "title": "Fails percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(num_failures * 100) / num_requests"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "avg_response_time" }
   ]
  },
  {
   "title": "Min response time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "min_response_time" }
   ]
  },
  {
   "title": "Max response time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max_response_time" }
   ]
  },
  {
   "title": "Avg RPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rps" }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 14 },
   "targets": [
    { "expr": "locust_errors" }
   ]
  }
 ]
}